---
- name: Include Debian tasks
  include: Debian.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

- name: Include CentOS tasks
  include: CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Download elasticsearch_exporter
  unarchive:
    src: "https://github.com/justwatchcom/elasticsearch_exporter/releases/download/\
      v{{ elasticsearch_exporter_version }}/elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64.tar.gz"
    dest: /usr/sbin/
    remote_src: true
    extra_opts:
      - --strip-components
      - '1'
      - "elasticsearch_exporter-{{ elasticsearch_exporter_version }}.linux-amd64/elasticsearch_exporter"
  notify:
    - restart elasticsearch_exporter

- name: Template elasticsearch_exporter systemd unit
  template:
    src: exporter.service.j2
    dest: /etc/systemd/system/elasticsearch_exporter.service
  notify:
    - systemd daemon-reload
    - restart elasticsearch_exporter

- name: Template elasticsearch config
  template:
    src: elasticsearch.yml.j2
    dest: /etc/elasticsearch/elasticsearch.yml
  notify:
    - restart elasticsearch
